pref("extensions.reader.first_run", true);
pref("extensions.reader.color_scheme", "light");
pref("extensions.reader.color_scheme.values", "[\"light\", \"dark\", \"sepia\"]");
pref("extensions.reader.content_width", 3);
pref("extensions.reader.errors.includeURLs", true);
pref("extensions.reader.font_size", 5);
pref("extensions.reader.font_type", "sans-serif");
pref("extensions.reader.has_used_toolbar", false);
pref("extensions.reader.line_height", 4);
pref("extensions.reader.parse-node-limit", 0);
pref("extensions.reader.parse-on-load.enabled", true);
pref("extensions.reader.parse-on-load.force-enabled", false);
pref("extensions.reader.toolbar.vertical", true);
pref("extensions.reader.location.urlbar", false);
pref("extensions.reader.hotkey.enabled", true);
